import type { Language, LocalizedText } from "@kierratysappi/domain";

const fi = {
  appName: "KierrätysAppi",
  tagline: "Pakkauksesta oikeaan paikkaan",
  introEyebrow: "SUOMEN LAJITTELUAPURI",
  introTitle: "Lue pakkaus.\nTiedä minne se kuuluu.",
  introBody:
    "Skannaa elintarvikkeen viivakoodi. Kun yhteisötietoa löytyy, saat osakohtaisen ohjeen, lähteen ja tiedon siitä, mitä pitää vielä tarkistaa.",
  privacySummary: "Ei tiliä. Ei mainosseurantaa. Kamerakuvaa ei lähetetä.",
  languageLabel: "Kieli",
  finnish: "Suomi",
  english: "English",
  scanAction: "Skannaa pakkaus",
  cameraTitle: "Skannaa viivakoodi",
  cameraEyebrow: "KAMERA / VIIVAKOODI",
  cameraPurpose:
    "Haemme elintarvikkeen tuotetietoa viivakoodilla. Kamerakuvaa ei lähetetä minnekään.",
  cameraAction: "Avaa kamera",
  cameraInstruction: "Aseta EAN- tai GTIN-koodi kehyksen sisään",
  cameraFrameLabel: "Viivakoodin kohdistuskehys",
  cameraPermissionTitle: "Kamera vain viivakoodille",
  cameraPermissionBody:
    "Lupa pyydetään vasta nyt, koska haluat skannata. Sovellus käsittelee viivakoodin laitteella eikä tallenna kamerakuvaa.",
  cameraDenied: "Kameran käyttö ei ole sallittu. Voit avata asetukset tai syöttää koodin käsin.",
  openSettings: "Avaa asetukset",
  manualEntry: "Syötä koodi käsin",
  gtinLabel: "EAN- tai GTIN-koodi",
  gtinHint: "8, 12, 13 tai 14 numeroa",
  lookupAction: "Hae tuote",
  invalidGtin: "Tarkista koodin numerot ja tarkistusnumero.",
  loading: "Haetaan tuotetta ja lajitteluohjeita…",
  loadingDetail: "Tarkistamme tuotetiedot ja Suomen pakkaussäännöt.",
  notFoundTitle: "Tuotetta ei löytynyt",
  notFoundBody:
    "Emme arvaa tuotetta. Voit tarkistaa koodin tai hakea yleisohjeen materiaalin mukaan.",
  packagingMissingTitle: "Pakkaustiedot puuttuvat",
  packagingMissingBody: "Tuote löytyi, mutta pakkauksen osista ei ole riittäviä tietoja.",
  providerUnavailableTitle: "Tietolähde ei vastaa",
  providerUnavailableBody:
    "Yritä hetken kuluttua uudelleen. Tätä ei merkitty tuntemattomaksi tuotteeksi.",
  offlineEyebrow: "EI VERKKOA / PAIKALLINEN",
  invalidEyebrow: "KOODI / VIRHEELLINEN",
  emptyScanEyebrow: "SKANNAUS / EI TULOSTA",
  unknownProductEyebrow: "TUOTE / TUNTEMATON",
  unavailableSourceEyebrow: "LÄHDE / EI SAATAVILLA",
  offlineTitle: "Ei verkkoyhteyttä",
  offlineBody:
    "Koodi säilytettiin sovelluksen paikallisessa tallennustilassa uutta yritystä varten.",
  retry: "Yritä uudelleen",
  scanAnother: "Skannaa toinen",
  checkCode: "Tarkista koodi",
  productLabel: "TUOTE",
  packagingParts: "Pakkauksen osat",
  destinationLabel: "Minne",
  preparationLabel: "Näin valmistelet",
  whyLabel: "Miksi tämä ohje",
  needsCheckLabel: "Tarkista pakkauksesta",
  possibleDestinations: "Mahdolliset paikat",
  dataSourceLabel: "Tuotetiedon lähde",
  dataLicenseLabel: "Tietokannan lisenssi",
  dataAttributionLabel: "Tekijätieto",
  communityDataLabel: "Yhteisön tuottamaa tietoa",
  ruleSourceLabel: "Lajittelusäännön lähde",
  lastRetrievedLabel: "Haettu",
  cachedLabel: "Välimuistissa",
  liveLabel: "Haettu nyt",
  manualComponentAction: "Tunnista osa käsin",
  materialCodeAction: "Tunnista materiaalikoodi",
  materialCodeEyebrow: "MERKINTÄ / PAIKALLINEN",
  materialCodeTitle: "Lue pakkauksen materiaalikoodi",
  materialCodeBody:
    "Kirjoita yksi pakkauksessa näkyvä koodi, esimerkiksi 05 PP tai PAP 21. Koodi käsitellään vain tällä laitteella.",
  materialCodeLabel: "Pakkauksessa näkyvä koodi",
  materialCodeHint: "Kirjoita sekä lyhenne että numero, jos molemmat näkyvät.",
  materialCodeParseAction: "Tarkista koodi",
  materialCodeRecognized: "Koodi tunnistettu — vahvista pakkauksesta",
  materialCodeRecognizedBody:
    "Tunnistus kertoo materiaaliryhmän, mutta ei yksin todista pakkauksen muotoa, pantillisuutta tai keräyskelpoisuutta.",
  materialCodeConfirmAction: "Näen tämän koodin pakkauksessa",
  materialCodeAmbiguousTitle: "Koodissa on vielä epäselvyyttä",
  materialCodeAmbiguousBody:
    "Emme valitse useasta tai ristiriitaisesta merkinnästä puolestasi. Tarkista yksi kokonainen koodi pakkauksesta.",
  materialCodeUnknownTitle: "Koodia ei tunnistettu",
  materialCodeUnknownBody:
    "Emme arvaa tuntematonta tai määrittelemätöntä koodia. Voit tunnistaa pakkauksen osan käsin.",
  materialCodeCandidates: "Mahdolliset täydelliset koodit",
  materialCodeLocalNote: "Teksti käsitellään paikallisesti. Kuvaa ei oteta eikä lähetetä.",
  materialCodeSource: "Merkintäjärjestelmä",
  materialGuideAction: "Avaa materiaalien yleisohje",
  materialGuideTitle: "Yleisohje ilman verkkoa",
  materialGuideBody: "Tarkistetut valtakunnalliset perusohjeet pakkauksille.",
  materialGuideEyebrow: "YLEISOHJE / SUOMI",
  materialPlastic: "Muovipakkaus",
  materialCarton: "Kartonkipakkaus",
  materialGlass: "Lasipakkaus",
  materialMetal: "Metallipakkaus",
  materialPaper: "Paperipakkaus",
  materialWood: "Puupakkaus",
  materialComposite: "Yhdistelmämateriaali",
  materialOther: "Muu materiaali",
  materialUnknown: "Tuntematon materiaali",
  guidePlastic: "Tyhjä pakkaus. Pienet ruokatahrat eivät haittaa. Irrota helposti irtoavat osat.",
  guideCarton: "Tyhjennä, huuhtele tarvittaessa, valuta ja litistä.",
  guideGlass: "Vain tyhjät lasipullot ja -purkit. Poista korkit ja kannet.",
  guideMetal: "Tyhjä metallipakkaus. Painepakkaus vain täysin tyhjänä.",
  depositCaution: "Pantillinen pullo tai tölkki kuuluu ensisijaisesti palautusautomaattiin.",
  selectMaterialTitle: "Mistä osa on tehty?",
  selectMaterialBody:
    "Valitse vain tieto, jonka näet pakkauksesta. Emme täytä puuttuvaa tietoa arvauksella.",
  shapeLabel: "Muoto",
  shapeBottle: "Pullo",
  shapeCan: "Tölkki",
  shapeJar: "Purkki",
  shapeOther: "Muu / en tiedä",
  depositLabel: "Onko suomalainen panttimerkki?",
  answerYes: "Kyllä",
  answerNo: "Ei",
  answerUnknown: "En tiedä",
  showGuidance: "Näytä ohje",
  localObservation: "Käyttäjän vahvistama tieto tällä laitteella",
  manualObservationEyebrow: "KÄSIN / HAVAITTU",
  feedbackEyebrow: "PALAUTE / PAIKALLINEN LUONNOS",
  identifierExact: "TUNNISTE / TARKKA",
  identifierGroup: "TUNNISTE / RYHMÄ",
  unknownValue: "TUNTEMATON",
  confidenceVerified: "Tarkistettu sääntö",
  confidenceHigh: "Hyvät pakkaustiedot",
  confidenceMedium: "Osittaiset pakkaustiedot",
  confidenceLow: "Tarkista pakkauksesta",
  confidenceUnknown: "Ei varmistettua tietoa",
  sourceLabel: "Lähde",
  checkedLabel: "Tarkistettu",
  historyTitle: "Historia",
  recentScans: "Viimeisimmät haut",
  historyOff: "Paikallinen historia on pois päältä.",
  historyOn:
    "Historia tallennetaan sovelluksen paikalliseen tallennustilaan. Käyttöjärjestelmän varmuuskopio voi sisältää sen.",
  enableHistory: "Ota paikallinen historia käyttöön",
  disableHistory: "Poista historia käytöstä",
  clearHistory: "Tyhjennä historia",
  clearHistoryConfirmTitle: "Tyhjennetäänkö historia?",
  clearHistoryConfirmBody: "Tallennetut haut poistetaan pysyvästi tältä laitteelta.",
  clearHistoryConfirmAction: "Tyhjennä",
  openResult: "Avaa",
  emptyHistory: "Ei tallennettuja hakuja.",
  localOnly: "Sovelluksen paikallinen tallennustila",
  correctionAction: "Ilmoita virheestä",
  feedbackTitle: "Ilmoita virheestä",
  feedbackBody:
    "Kerro mikä tieto on väärin. Luonnos tallennetaan nyt vain laitteellesi; lähetys avataan vasta, kun suostumus- ja moderointipalvelu on käytössä.",
  feedbackWrongProduct: "Väärä tuote",
  feedbackWrongPackaging: "Väärä pakkaustieto",
  feedbackWrongSorting: "Väärä lajitteluohje",
  feedbackMissing: "Tieto puuttuu",
  feedbackNote: "Lisätieto (valinnainen)",
  feedbackPrivacyCaution: "Älä kirjoita nimeä, yhteystietoja tai muuta henkilötietoa luonnokseen.",
  saveDraft: "Tallenna luonnos laitteelle",
  draftSaved: "Luonnos tallennettu",
  legalAction: "Tietosuoja ja ehdot",
  privacyTitle: "Tietosuojailmoitus",
  termsTitle: "Käyttöehdot",
  legalReview: "LUONNOS — ODOTTAA JURIDISTA TARKISTUSTA",
  privacyDraft:
    "Perushaku ei vaadi tiliä. Viivakoodi lähetetään KierrätysAppin palvelimelle ja edelleen Open Food Factsille tuotetietojen hakua varten. Palvelin voi säilyttää viivakoodiin liittyvää hakutulosta prosessimuistissa enintään kuusi tuntia ja IP-osoitetta väärinkäytön estoon enintään minuutin; rutiinipyyntöjä ei lokiteta. Mainos- tai käyttöanalytiikkaa ei ole. Historia ja palauteluonnokset ovat paikallisia, mutta käyttöjärjestelmän varmuuskopio voi sisältää ne; kaikki paikalliset tiedot voi poistaa alta.",
  termsDraft:
    "Lajitteluohje perustuu ilmoitettuihin lähteisiin ja voi vaatia pakkauksen tarkistamista. Paikallinen jätehuolto ja pakkauksen vaarallisuusohjeet ovat etusijalla.",
  deleteLocalData: "Poista kaikki paikalliset tiedot",
  deleteLocalDataBody:
    "Poistaa historian, odottavat haut, palauteluonnokset, kielivalinnan ja muut KierrätysAppin asetukset tältä laitteelta.",
  deleteLocalDataConfirmTitle: "Poistetaanko kaikki paikalliset tiedot?",
  deleteLocalDataConfirmBody: "Toimintoa ei voi perua.",
  deleteLocalDataConfirmAction: "Poista tiedot",
  localDataDeleted: "Kaikki KierrätysAppin paikalliset tiedot poistettiin.",
  cancel: "Peruuta",
  back: "Takaisin",
  close: "Sulje",
} as const;

const en: Record<keyof typeof fi, string> = {
  appName: "KierrätysAppi",
  tagline: "From package to the right place",
  introEyebrow: "FINLAND'S SORTING COMPANION",
  introTitle: "Read the package.\nKnow where it belongs.",
  introBody:
    "Scan a food-product barcode. When community data is available, you get component guidance, sources, and an honest note about what still needs checking.",
  privacySummary: "No account. No ad tracking. Camera frames stay on device.",
  languageLabel: "Language",
  finnish: "Suomi",
  english: "English",
  scanAction: "Scan a package",
  cameraTitle: "Scan a barcode",
  cameraEyebrow: "CAMERA / BARCODE",
  cameraPurpose: "We look up food-product data by barcode. Camera frames are not uploaded.",
  cameraAction: "Open camera",
  cameraInstruction: "Place the EAN or GTIN inside the frame",
  cameraFrameLabel: "Barcode alignment frame",
  cameraPermissionTitle: "Camera only for the barcode",
  cameraPermissionBody:
    "Permission is requested now because you chose to scan. The barcode is decoded on device and camera frames are not stored.",
  cameraDenied: "Camera access is off. Open settings or enter the code manually.",
  openSettings: "Open settings",
  manualEntry: "Enter code manually",
  gtinLabel: "EAN or GTIN code",
  gtinHint: "8, 12, 13, or 14 digits",
  lookupAction: "Find product",
  invalidGtin: "Check the digits and check digit.",
  loading: "Finding the product and sorting guidance…",
  loadingDetail: "Checking product data and Finnish packaging rules.",
  notFoundTitle: "Product not found",
  notFoundBody: "We do not guess the product. Check the code or use general material guidance.",
  packagingMissingTitle: "Packaging data is missing",
  packagingMissingBody:
    "The product was found, but there is not enough information about its parts.",
  providerUnavailableTitle: "Data source unavailable",
  providerUnavailableBody: "Try again shortly. This was not recorded as an unknown product.",
  offlineEyebrow: "OFFLINE / LOCAL",
  invalidEyebrow: "CODE / INVALID",
  emptyScanEyebrow: "SCAN / EMPTY",
  unknownProductEyebrow: "PRODUCT / UNKNOWN",
  unavailableSourceEyebrow: "SOURCE / UNAVAILABLE",
  offlineTitle: "No network connection",
  offlineBody: "The code was kept in the app's local storage for another attempt.",
  retry: "Try again",
  scanAnother: "Scan another",
  checkCode: "Check the code",
  productLabel: "PRODUCT",
  packagingParts: "Packaging parts",
  destinationLabel: "Where it goes",
  preparationLabel: "Prepare it like this",
  whyLabel: "Why this guidance",
  needsCheckLabel: "Check on the package",
  possibleDestinations: "Possible destinations",
  dataSourceLabel: "Product data source",
  dataLicenseLabel: "Database license",
  dataAttributionLabel: "Attribution",
  communityDataLabel: "Community-contributed data",
  ruleSourceLabel: "Sorting rule source",
  lastRetrievedLabel: "Retrieved",
  cachedLabel: "From cache",
  liveLabel: "Retrieved now",
  manualComponentAction: "Identify a part manually",
  materialCodeAction: "Identify a material code",
  materialCodeEyebrow: "MARKING / LOCAL",
  materialCodeTitle: "Read the package material code",
  materialCodeBody:
    "Enter one code visible on the package, such as 05 PP or PAP 21. The code is processed only on this device.",
  materialCodeLabel: "Code visible on the package",
  materialCodeHint: "Enter both the abbreviation and number when both are visible.",
  materialCodeParseAction: "Check code",
  materialCodeRecognized: "Code recognized — confirm it on the package",
  materialCodeRecognizedBody:
    "Recognition identifies a material group, but does not by itself prove shape, deposit status, or collection eligibility.",
  materialCodeConfirmAction: "I see this code on the package",
  materialCodeAmbiguousTitle: "The code is still ambiguous",
  materialCodeAmbiguousBody:
    "We do not choose between multiple or conflicting markings for you. Check one complete code on the package.",
  materialCodeUnknownTitle: "Code not recognized",
  materialCodeUnknownBody:
    "We do not guess an unknown or undefined code. You can identify the package part manually.",
  materialCodeCandidates: "Possible complete codes",
  materialCodeLocalNote: "Text is processed locally. No image is captured or uploaded.",
  materialCodeSource: "Marking scheme",
  materialGuideAction: "Open the general material guide",
  materialGuideTitle: "Offline general guide",
  materialGuideBody: "Reviewed nationwide basics for packaging.",
  materialGuideEyebrow: "OFFLINE GUIDE / FINLAND",
  materialPlastic: "Plastic packaging",
  materialCarton: "Carton packaging",
  materialGlass: "Glass packaging",
  materialMetal: "Metal packaging",
  materialPaper: "Paper packaging",
  materialWood: "Wood packaging",
  materialComposite: "Composite material",
  materialOther: "Other material",
  materialUnknown: "Unknown material",
  guidePlastic: "Empty packaging. Small food stains are fine. Detach parts that come off easily.",
  guideCarton: "Empty, rinse when needed, drain, and flatten.",
  guideGlass: "Empty glass bottles and jars only. Remove caps and lids.",
  guideMetal: "Empty metal packaging. Aerosols only when completely empty.",
  depositCaution: "A deposit bottle or can goes to a retail return point first.",
  selectMaterialTitle: "What is this part made of?",
  selectMaterialBody:
    "Select only what you can see on the package. Missing facts are not filled in by guessing.",
  shapeLabel: "Shape",
  shapeBottle: "Bottle",
  shapeCan: "Can",
  shapeJar: "Jar",
  shapeOther: "Other / not sure",
  depositLabel: "Does it show a Finnish deposit mark?",
  answerYes: "Yes",
  answerNo: "No",
  answerUnknown: "Not sure",
  showGuidance: "Show guidance",
  localObservation: "User-confirmed information on this device",
  manualObservationEyebrow: "MANUAL / OBSERVED",
  feedbackEyebrow: "FEEDBACK / LOCAL DRAFT",
  identifierExact: "ID / EXACT",
  identifierGroup: "ID / GROUP",
  unknownValue: "UNKNOWN",
  confidenceVerified: "Reviewed rule",
  confidenceHigh: "Good packaging data",
  confidenceMedium: "Partial packaging data",
  confidenceLow: "Check the package",
  confidenceUnknown: "No confirmed information",
  sourceLabel: "Source",
  checkedLabel: "Checked",
  historyTitle: "History",
  recentScans: "Recent lookups",
  historyOff: "Local history is off.",
  historyOn:
    "History is stored in the app's local storage. An operating-system backup may include it.",
  enableHistory: "Enable local history",
  disableHistory: "Disable history",
  clearHistory: "Clear history",
  clearHistoryConfirmTitle: "Clear history?",
  clearHistoryConfirmBody: "Saved lookups will be permanently removed from this device.",
  clearHistoryConfirmAction: "Clear",
  openResult: "Open",
  emptyHistory: "No saved lookups.",
  localOnly: "Local app storage",
  correctionAction: "Report a problem",
  feedbackTitle: "Report a problem",
  feedbackBody:
    "Tell us which field is wrong. For now, the draft stays only on your device; sending will open once consent and moderation services are ready.",
  feedbackWrongProduct: "Wrong product",
  feedbackWrongPackaging: "Wrong packaging data",
  feedbackWrongSorting: "Wrong sorting guidance",
  feedbackMissing: "Information missing",
  feedbackNote: "More detail (optional)",
  feedbackPrivacyCaution:
    "Do not include your name, contact details, or other personal data in the draft.",
  saveDraft: "Save draft on device",
  draftSaved: "Draft saved",
  legalAction: "Privacy and terms",
  privacyTitle: "Privacy notice",
  termsTitle: "Terms of use",
  legalReview: "DRAFT — REQUIRES LEGAL REVIEW",
  privacyDraft:
    "Basic lookup needs no account. The barcode is sent to the KierrätysAppi server and then to Open Food Facts to find product data. The server may retain a barcode-linked lookup result in process memory for up to six hours and an IP address for abuse prevention for up to one minute; routine requests are not logged. There is no advertising or usage analytics. History and feedback drafts are local, but an operating-system backup may include them; all local data can be deleted below.",
  termsDraft:
    "Guidance is based on the cited sources and may require checking the package. Local waste-service and hazardous-product instructions take precedence.",
  deleteLocalData: "Delete all local data",
  deleteLocalDataBody:
    "Removes history, pending lookups, feedback drafts, the language choice, and other KierrätysAppi settings from this device.",
  deleteLocalDataConfirmTitle: "Delete all local data?",
  deleteLocalDataConfirmBody: "This action cannot be undone.",
  deleteLocalDataConfirmAction: "Delete data",
  localDataDeleted: "All KierrätysAppi local data was deleted.",
  cancel: "Cancel",
  back: "Back",
  close: "Close",
};

export const messages = { fi, en } as const;
export type MessageKey = keyof typeof fi;

export function translate(language: Language, key: MessageKey): string {
  return messages[language][key];
}

export function localizedText(language: Language, text: LocalizedText): string {
  return text[language];
}
