import type { Language, LocalizedText } from "@kierratysappi/domain";

const fi = {
  appName: "KierrätysAppi",
  tagline: "Pakkauksesta oikeaan paikkaan",
  introEyebrow: "SUOMEN LAJITTELUAPURI",
  introTitle: "Lue pakkaus.\nTiedä minne se kuuluu.",
  introBody:
    "Skannaa tuotteen viivakoodi. Saat osakohtaisen ohjeen, lähteen ja tiedon siitä, mitä pitää vielä tarkistaa.",
  privacySummary: "Ei tiliä. Ei mainosseurantaa. Kamerakuvaa ei lähetetä.",
  languageLabel: "Kieli",
  finnish: "Suomi",
  english: "English",
  scanAction: "Skannaa pakkaus",
  cameraTitle: "Skannaa viivakoodi",
  cameraPurpose: "Tunnistamme tuotteen viivakoodista. Kamerakuvaa ei lähetetä minnekään.",
  cameraAction: "Avaa kamera",
  cameraInstruction: "Aseta EAN- tai GTIN-koodi kehyksen sisään",
  cameraFrameLabel: "Viivakoodin kohdistuskehys",
  cameraPermissionTitle: "Kamera vain viivakoodille",
  cameraPermissionBody:
    "Lupa pyydetään vasta nyt, koska haluat skannata. Sovellus käsittelee viivakoodin laitteella eikä tallenna kamerakuvaa.",
  cameraDenied: "Kameran käyttö ei ole sallittu. Voit avata asetukset tai syöttää koodin käsin.",
  openSettings: "Avaa asetukset",
  manualEntry: "Syötä koodi käsin",
  gtinLabel: "EAN- tai GTIN-koodi",
  gtinHint: "8, 12, 13 tai 14 numeroa",
  lookupAction: "Hae tuote",
  invalidGtin: "Tarkista koodin numerot ja tarkistusnumero.",
  loading: "Haetaan tuotetta ja lajitteluohjeita…",
  loadingDetail: "Tarkistamme tuotetiedot ja Suomen pakkaussäännöt.",
  notFoundTitle: "Tuotetta ei löytynyt",
  notFoundBody:
    "Emme arvaa tuotetta. Voit tarkistaa koodin tai hakea yleisohjeen materiaalin mukaan.",
  packagingMissingTitle: "Pakkaustiedot puuttuvat",
  packagingMissingBody: "Tuote löytyi, mutta pakkauksen osista ei ole riittäviä tietoja.",
  providerUnavailableTitle: "Tietolähde ei vastaa",
  providerUnavailableBody:
    "Yritä hetken kuluttua uudelleen. Tätä ei merkitty tuntemattomaksi tuotteeksi.",
  offlineTitle: "Ei verkkoyhteyttä",
  offlineBody: "Koodi säilytettiin vain tällä laitteella uutta yritystä varten.",
  retry: "Yritä uudelleen",
  scanAnother: "Skannaa toinen",
  checkCode: "Tarkista koodi",
  productLabel: "TUOTE",
  packagingParts: "Pakkauksen osat",
  destinationLabel: "Minne",
  preparationLabel: "Näin valmistelet",
  whyLabel: "Miksi tämä ohje",
  needsCheckLabel: "Tarkista pakkauksesta",
  possibleDestinations: "Mahdolliset paikat",
  dataSourceLabel: "Tuotetiedon lähde",
  ruleSourceLabel: "Lajittelusäännön lähde",
  lastRetrievedLabel: "Haettu",
  cachedLabel: "Välimuistissa",
  liveLabel: "Haettu nyt",
  manualComponentAction: "Tunnista osa käsin",
  photoLabelAction: "Kuvaa kierrätysmerkintä",
  photoConsentNote: "Kuvaa ei lähetetä ilman erillistä suostumusta.",
  materialGuideAction: "Avaa materiaalien yleisohje",
  materialGuideTitle: "Yleisohje ilman verkkoa",
  materialGuideBody: "Tarkistetut valtakunnalliset perusohjeet pakkauksille.",
  materialPlastic: "Muovipakkaus",
  materialCarton: "Kartonkipakkaus",
  materialGlass: "Lasipakkaus",
  materialMetal: "Metallipakkaus",
  guidePlastic: "Tyhjä pakkaus. Pienet ruokatahrat eivät haittaa. Irrota helposti irtoavat osat.",
  guideCarton: "Tyhjennä, huuhtele tarvittaessa, valuta ja litistä.",
  guideGlass: "Vain tyhjät lasipullot ja -purkit. Poista korkit ja kannet.",
  guideMetal: "Tyhjä metallipakkaus. Painepakkaus vain täysin tyhjänä.",
  depositCaution: "Pantillinen pullo tai tölkki kuuluu ensisijaisesti palautusautomaattiin.",
  selectMaterialTitle: "Mistä osa on tehty?",
  selectMaterialBody:
    "Valitse vain tieto, jonka näet pakkauksesta. Emme täytä puuttuvaa tietoa arvauksella.",
  shapeLabel: "Muoto",
  shapeBottle: "Pullo",
  shapeCan: "Tölkki",
  shapeJar: "Purkki",
  shapeOther: "Muu / en tiedä",
  depositLabel: "Onko suomalainen panttimerkki?",
  answerYes: "Kyllä",
  answerNo: "Ei",
  answerUnknown: "En tiedä",
  showGuidance: "Näytä ohje",
  localObservation: "Käyttäjän vahvistama tieto tällä laitteella",
  confidenceVerified: "Tarkistettu sääntö",
  confidenceHigh: "Hyvät pakkaustiedot",
  confidenceMedium: "Osittaiset pakkaustiedot",
  confidenceLow: "Tarkista pakkauksesta",
  confidenceUnknown: "Ei varmistettua tietoa",
  sourceLabel: "Lähde",
  checkedLabel: "Tarkistettu",
  historyTitle: "Historia",
  recentScans: "Viimeisimmät haut",
  historyOff: "Paikallinen historia on pois päältä.",
  historyOn: "Historia tallennetaan vain tälle laitteelle.",
  enableHistory: "Ota paikallinen historia käyttöön",
  disableHistory: "Poista historia käytöstä",
  clearHistory: "Tyhjennä historia",
  emptyHistory: "Ei tallennettuja hakuja.",
  localOnly: "Vain tällä laitteella",
  correctionAction: "Ilmoita virheestä",
  feedbackTitle: "Ilmoita virheestä",
  feedbackBody:
    "Kerro mikä tieto on väärin. Luonnos tallennetaan nyt vain laitteellesi; lähetys avataan vasta, kun suostumus- ja moderointipalvelu on käytössä.",
  feedbackWrongProduct: "Väärä tuote",
  feedbackWrongPackaging: "Väärä pakkaustieto",
  feedbackWrongSorting: "Väärä lajitteluohje",
  feedbackMissing: "Tieto puuttuu",
  feedbackNote: "Lisätieto (valinnainen)",
  saveDraft: "Tallenna luonnos laitteelle",
  draftSaved: "Luonnos tallennettu",
  legalAction: "Tietosuoja ja ehdot",
  privacyTitle: "Tietosuojailmoitus",
  termsTitle: "Käyttöehdot",
  legalReview: "LUONNOS — ODOTTAA JURIDISTA TARKISTUSTA",
  privacyDraft:
    "Perushaku ei vaadi tiliä. Viivakoodi lähetetään KierrätysAppin palvelimelle tuotetietojen hakua varten, mutta raakaa hakuhistoriaa ei lähetetä analytiikkaan. Paikallinen historia on vapaaehtoinen.",
  termsDraft:
    "Lajitteluohje perustuu ilmoitettuihin lähteisiin ja voi vaatia pakkauksen tarkistamista. Paikallinen jätehuolto ja pakkauksen vaarallisuusohjeet ovat etusijalla.",
  back: "Takaisin",
  close: "Sulje",
} as const;

const en: Record<keyof typeof fi, string> = {
  appName: "KierrätysAppi",
  tagline: "From package to the right place",
  introEyebrow: "FINLAND'S SORTING COMPANION",
  introTitle: "Read the package.\nKnow where it belongs.",
  introBody:
    "Scan a product barcode for component-level guidance, sources, and an honest note about what still needs checking.",
  privacySummary: "No account. No ad tracking. Camera frames stay on device.",
  languageLabel: "Language",
  finnish: "Suomi",
  english: "English",
  scanAction: "Scan a package",
  cameraTitle: "Scan a barcode",
  cameraPurpose: "We identify the product from its barcode. Camera frames are not uploaded.",
  cameraAction: "Open camera",
  cameraInstruction: "Place the EAN or GTIN inside the frame",
  cameraFrameLabel: "Barcode alignment frame",
  cameraPermissionTitle: "Camera only for the barcode",
  cameraPermissionBody:
    "Permission is requested now because you chose to scan. The barcode is decoded on device and camera frames are not stored.",
  cameraDenied: "Camera access is off. Open settings or enter the code manually.",
  openSettings: "Open settings",
  manualEntry: "Enter code manually",
  gtinLabel: "EAN or GTIN code",
  gtinHint: "8, 12, 13, or 14 digits",
  lookupAction: "Find product",
  invalidGtin: "Check the digits and check digit.",
  loading: "Finding the product and sorting guidance…",
  loadingDetail: "Checking product data and Finnish packaging rules.",
  notFoundTitle: "Product not found",
  notFoundBody: "We do not guess the product. Check the code or use general material guidance.",
  packagingMissingTitle: "Packaging data is missing",
  packagingMissingBody:
    "The product was found, but there is not enough information about its parts.",
  providerUnavailableTitle: "Data source unavailable",
  providerUnavailableBody: "Try again shortly. This was not recorded as an unknown product.",
  offlineTitle: "No network connection",
  offlineBody: "The code was kept only on this device for another attempt.",
  retry: "Try again",
  scanAnother: "Scan another",
  checkCode: "Check the code",
  productLabel: "PRODUCT",
  packagingParts: "Packaging parts",
  destinationLabel: "Where it goes",
  preparationLabel: "Prepare it like this",
  whyLabel: "Why this guidance",
  needsCheckLabel: "Check on the package",
  possibleDestinations: "Possible destinations",
  dataSourceLabel: "Product data source",
  ruleSourceLabel: "Sorting rule source",
  lastRetrievedLabel: "Retrieved",
  cachedLabel: "From cache",
  liveLabel: "Retrieved now",
  manualComponentAction: "Identify a part manually",
  photoLabelAction: "Photograph the recycling label",
  photoConsentNote: "No image is uploaded without separate consent.",
  materialGuideAction: "Open the general material guide",
  materialGuideTitle: "Offline general guide",
  materialGuideBody: "Reviewed nationwide basics for packaging.",
  materialPlastic: "Plastic packaging",
  materialCarton: "Carton packaging",
  materialGlass: "Glass packaging",
  materialMetal: "Metal packaging",
  guidePlastic: "Empty packaging. Small food stains are fine. Detach parts that come off easily.",
  guideCarton: "Empty, rinse when needed, drain, and flatten.",
  guideGlass: "Empty glass bottles and jars only. Remove caps and lids.",
  guideMetal: "Empty metal packaging. Aerosols only when completely empty.",
  depositCaution: "A deposit bottle or can goes to a retail return point first.",
  selectMaterialTitle: "What is this part made of?",
  selectMaterialBody:
    "Select only what you can see on the package. Missing facts are not filled in by guessing.",
  shapeLabel: "Shape",
  shapeBottle: "Bottle",
  shapeCan: "Can",
  shapeJar: "Jar",
  shapeOther: "Other / not sure",
  depositLabel: "Does it show a Finnish deposit mark?",
  answerYes: "Yes",
  answerNo: "No",
  answerUnknown: "Not sure",
  showGuidance: "Show guidance",
  localObservation: "User-confirmed information on this device",
  confidenceVerified: "Reviewed rule",
  confidenceHigh: "Good packaging data",
  confidenceMedium: "Partial packaging data",
  confidenceLow: "Check the package",
  confidenceUnknown: "No confirmed information",
  sourceLabel: "Source",
  checkedLabel: "Checked",
  historyTitle: "History",
  recentScans: "Recent lookups",
  historyOff: "Local history is off.",
  historyOn: "History is stored only on this device.",
  enableHistory: "Enable local history",
  disableHistory: "Disable history",
  clearHistory: "Clear history",
  emptyHistory: "No saved lookups.",
  localOnly: "Only on this device",
  correctionAction: "Report a problem",
  feedbackTitle: "Report a problem",
  feedbackBody:
    "Tell us which field is wrong. For now, the draft stays only on your device; sending will open once consent and moderation services are ready.",
  feedbackWrongProduct: "Wrong product",
  feedbackWrongPackaging: "Wrong packaging data",
  feedbackWrongSorting: "Wrong sorting guidance",
  feedbackMissing: "Information missing",
  feedbackNote: "More detail (optional)",
  saveDraft: "Save draft on device",
  draftSaved: "Draft saved",
  legalAction: "Privacy and terms",
  privacyTitle: "Privacy notice",
  termsTitle: "Terms of use",
  legalReview: "DRAFT — REQUIRES LEGAL REVIEW",
  privacyDraft:
    "Basic lookup needs no account. The barcode is sent to the KierrätysAppi server to find product data, but raw lookup history is not sent to analytics. Local history is optional.",
  termsDraft:
    "Guidance is based on the cited sources and may require checking the package. Local waste-service and hazardous-product instructions take precedence.",
  back: "Back",
  close: "Close",
};

export const messages = { fi, en } as const;
export type MessageKey = keyof typeof fi;

export function translate(language: Language, key: MessageKey): string {
  return messages[language][key];
}

export function localizedText(language: Language, text: LocalizedText): string {
  return text[language];
}
